In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data.csv')

df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [3]:
df.shape

(12, 6)

In [4]:
# get any column
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [5]:
df['Actor'][3]

'Ranbir Kapoor'

In [6]:
type(df['Actor'])

pandas.core.series.Series

In [7]:
# df[['Actor', 'IMDb']]

In [8]:
# select row by index

# loc : for labels
# iloc : for indices

df.loc[0] # from loc we can get by the custom index we have given like 'shayan', 'harry'...

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [9]:
df.iloc[0] # from iloc we get the data by normal indexing like 0, 1, 2

Actor                   Shah Rukh Khan
Film                           Pathaan
Year                              2023
Genre                           Action
BoxOffice(INR Crore)              1050
IMDb                               7.2
Name: 0, dtype: object

In [10]:
df.loc[0, 'IMDb'] # by labels

np.float64(7.2)

In [11]:
df.iloc[0, 5] # by indexing

np.float64(7.2)

In [12]:
# loc is inclusive of slicing | 0:3 gives 4 rows from 0 to 3
df.loc[0:3, ['Actor', 'IMDb', 'Film']]

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal
3   Ranbir Kapoor   5.6       Brahmastra

In [13]:
# iloc is exclusive of slicing | 0:3 gives 3 rows from 0 to 2
df.iloc[0:3, [0, 1, 5]]

            Actor             Film  IMDb
0  Shah Rukh Khan          Pathaan   7.2
1     Salman Khan  Tiger Zinda Hai   6.0
2      Aamir Khan           Dangal   8.4

In [14]:
df.at[0,'Actor']

'Shah Rukh Khan'

In [15]:
df.iat[0,0]

'Shah Rukh Khan'

## Quick filtering

In [21]:
df[df['IMDb'] > 6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [28]:
df[(df['IMDb'] > 6) & (df['Year'] > 2018)] # we can use logical operat & , |

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [29]:
df1 = df[df['IMDb'] > 6]['Actor']

In [25]:
# as you can see above the indexing is mis match over here you can use the difference of loc and iloc
df1.loc[2]

'Aamir Khan'

In [27]:
df1.iloc[1]

'Aamir Khan'

In [30]:
# Query
# this return a copy and not the view
df.query("IMDb > 6")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [31]:
df.query("IMDb > 7 and Year > 2018")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2