In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('data_cleaning_sample.csv')

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
# to find where your data is impty
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [5]:
# to see in which column how many null values you have
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [6]:
# to remove the data with null values
# this will simply remove all the rows having null data
df1 = df.dropna()

In [7]:
# df1.isnull().sum()
df1

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [8]:
# to remove the column having null data
df2 = df.dropna(axis=1)

In [9]:
df2

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [10]:
# we can add a default value to all the null values
df3 = df.fillna(0)

In [11]:
df3

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [12]:
# we can fill the missing values with the average
df['Age'].fillna(df['Age'].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [13]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [14]:
# forward fill
f_df = df.fillna(method='ffill')

C:\Users\shaya\AppData\Local\Temp\ipykernel_26536\499247219.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  f_df = df.fillna(method='ffill')

In [15]:
f_df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [16]:
f_df2 = df.ffill()

In [17]:
f_df2

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [18]:
# backward filling
b_df = df.bfill()

In [19]:
b_df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [20]:
# to identify the duplicated value
df_dup = df.copy()

In [21]:
df_dup

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [22]:
# identify duplicated
df_dup.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [23]:
df_dup

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [24]:
# to remove duplicates
df_dup = df_dup.drop_duplicates()

In [25]:
df_dup

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [26]:
# as you can see the index 3 is removed because of our modifications
# therefore we need to be carefull about these
df_dup.loc[2]

Name                     Bob
Age                     30.0
City             Los Angeles
Gender                     M
Email        bob@example.com
Join Date         15-06-2020
Name: 2, dtype: object

In [27]:
# this gives us error as the index 3 is been removed
# df_dup.loc[3]

In [28]:
df_dup.iloc[3]

Name                     David
Age                       22.0
City                    Mumbai
Gender                       M
Email        david@example.com
Join Date           12-11-2019
Name: 4, dtype: object

In [29]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [30]:
df['Name'].str.lower()

0      alice
1    charlie
2        bob
3    charlie
4      david
5        NaN
6      alice
7      alice
8    charlie
Name: Name, dtype: object

In [31]:
df['City'].str.contains('delhi', case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [32]:
df['Email'].str.split('@')

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [33]:
type(df['Email'].str.split('@')[0])

list

In [34]:
# we can also change the data type of a column
# here the age is in float, converting it with int
df_clean = df.dropna().copy()

In [35]:
df_clean

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [36]:
df_clean['Age'] = df_clean['Age'].astype(int)

In [37]:
df_clean

    Name  Age         City Gender              Email   Join Date
0  Alice   25     New York      F  alice@example.com  01-05-2021
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020
4  David   22       Mumbai      M  david@example.com  12-11-2019
6  Alice   25     New York      F  alice@example.com  01-05-2021
7  Alice   25     New York      F  alice@example.com  01-05-2021

## apply()

In [39]:
# using apply to create a column name Age Group
df_clean['Age Group'] = df_clean['Age'].apply(lambda x : 'Young' if x < 25 else 'Old')

In [40]:
df_clean

    Name  Age         City Gender              Email   Join Date Age Group
0  Alice   25     New York      F  alice@example.com  01-05-2021       Old
2    Bob   30  Los Angeles      M    bob@example.com  15-06-2020       Old
4  David   22       Mumbai      M  david@example.com  12-11-2019     Young
6  Alice   25     New York      F  alice@example.com  01-05-2021       Old
7  Alice   25     New York      F  alice@example.com  01-05-2021       Old

In [42]:
#  we can to the same using function

def is_minor(age):
    return 'Adult' if age > 25 else "Minor"

df_clean['Age group def func'] = df_clean['Age'].apply(is_minor)

In [43]:
df_clean

,Name,Age,City,Gender,Email,Join Date,Age Group,Age group def func
0,Alice,25,New York,F,alice@example.com,01-05-2021,Old,Minor
2,Bob,30,Los Angeles,M,bob@example.com,15-06-2020,Old,Adult
4,David,22,Mumbai,M,david@example.com,12-11-2019,Young,Minor
6,Alice,25,New York,F,alice@example.com,01-05-2021,Old,Minor
7,Alice,25,New York,F,alice@example.com,01-05-2021,Old,Minor

## map()

In [45]:
gender_map = {"M" : "Male", "F" : "Female", "O" : "Other"}

df_clean["Gender"] = df_clean["Gender"].map(gender_map)

df_clean

,Name,Age,City,Gender,Email,Join Date,Age Group,Age group def func
0,Alice,25,New York,Female,alice@example.com,01-05-2021,Old,Minor
2,Bob,30,Los Angeles,Male,bob@example.com,15-06-2020,Old,Adult
4,David,22,Mumbai,Male,david@example.com,12-11-2019,Young,Minor
6,Alice,25,New York,Female,alice@example.com,01-05-2021,Old,Minor
7,Alice,25,New York,Female,alice@example.com,01-05-2021,Old,Minor

In [52]:
df_clean["City"] = df_clean["City"].replace({"New York": "NY-city", "Mumbai": "Bombay"})

In [53]:
df_clean

,Name,Age,City,Gender,Email,Join Date,Age Group,Age group def func
0,Alice,25,NY-city,Female,alice@example.com,01-05-2021,Old,Minor
2,Bob,30,Los Angeles,Male,bob@example.com,15-06-2020,Old,Adult
4,David,22,Bombay,Male,david@example.com,12-11-2019,Young,Minor
6,Alice,25,NY-city,Female,alice@example.com,01-05-2021,Old,Minor
7,Alice,25,NY-city,Female,alice@example.com,01-05-2021,Old,Minor