In [1]:
import pandas as pd

employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [2]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [3]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [4]:
pd.merge(employees, departments, on="DeptID")  # Inner join : just give the common data from both table

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [5]:
pd.merge(employees, departments, on="DeptID", how="left") # left join

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [6]:
pd.merge(employees, departments, on="DeptID", how="right") # right join

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [7]:
pd.merge(employees, departments, on="DeptID", how="outer") # outer join

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [17]:
df1 = pd.DataFrame({"Name" : ["Alice", "Bob"], "Score" : [99, 56]})
df2 = pd.DataFrame({"Name" : ["Jack", "Jill"], "Age" : [12, 42]})

In [18]:
df1

    Name  Score
0  Alice     99
1    Bob     56

In [19]:
df2

   Name  Age
0  Jack   12
1  Jill   42

In [20]:
pd.concat([df1,df2])

    Name  Score   Age
0  Alice   99.0   NaN
1    Bob   56.0   NaN
0   Jack    NaN  12.0
1   Jill    NaN  42.0

In [21]:
pd.concat([df1,df2], axis=1)

    Name  Score  Name  Age
0  Alice     99  Jack   12
1    Bob     56  Jill   42

# when do we need concat
- When we have our data in multiple chunks.
- for example if we have multiple data from multiple csv, url, json, sql.
- we will create a different df and finally we can concat the data.