In [1]:
import pandas as pd

In [2]:
# read a csv file
df = pd.read_csv('data.csv')

df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df = df[df["IMDb"] > 6.0]

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
# this will create the csv file but the first column will be there of dataFrame index as shown above
df.to_csv("data_updated.csv")

In [9]:
# If you don't want to add the index as the first column
df.to_csv("data_updated_2.csv", index=False)

# Read json

In [10]:
df = pd.read_json("my.json")

In [11]:
df

   Id   Name                                Address
0   1  Alice  {'City': 'Mumbai', 'Pincode': 123231}
1   2   Lucy  {'City': 'Mumbai', 'Pincode': 123231}

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Id       2 non-null      int64
 1   Name     2 non-null      object
 2   Address  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [14]:
data = [
    {"Id" : 1, "Name" : "Alice", "Address" : {"City" : "Mumbai", "Pincode" : 123231}},
    {"Id" : 2, "Name" : "Lucy", "Address" : {"City" : "Mumbai", "Pincode" : 123231}}
]

In [15]:
df = pd.json_normalize(data)

In [16]:
df

   Id   Name Address.City  Address.Pincode
0   1  Alice       Mumbai           123231
1   2   Lucy       Mumbai           123231